name: Basic CI
on: 
  workflow_dispatch: 
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: print hello
        run: echo "Hello Tanishka, CI is working" 
      - name: Show date
        run: date
